### ISSUE TITLE
The sqrt function now collides with syntax in Swift

### ISSUE THREAD

**Issue by jamieatrkil** [attaswift/BigInt#103]
Would it be possible to change the syntax? Thx
<img width="857" alt="Screen Shot 2022-07-05 at 15 03 12" src="https://user-images.githubusercontent.com/6053611/177397691-e8a314d2-8045-45e1-87c8-b6bdd0809388.png">
.

**Comment by tgymnich** [comment]
BigInt does not define any function called sqrt.
