### ISSUE TITLE
Missing swift version

### ISSUE THREAD

**Issue by dongcp** [attaswift/BigInt#107]
Hi,
I'm importing the latest version via cocoapods but the IDE keeps throwing the following error when I try to run `pod install`:
`BigInt` does not specify a Swift version and none of the targets (`ios`) integrating it have the `SWIFT_VERSION` attribute set.
Could you please specify that Swift version for the library?
Thanks.

**Comment by tgymnich** [comment]
added in [5dde855](https://github.com/attaswift/BigInt/commit/5dde855ae20cf0e3c2395b85b8176cff875beab9)
