### ISSUE TITLE
Windows CI checkout error in 5.4.0

### ISSUE THREAD

**Issue by koliyo** [attaswift/BigInt#120]
The new file paths for generated documentation gives me errors during checkout of swift dependencies on github windows CI runners.

```
error: 'bigint': Couldn’t check out revision ‘88071df9f27361b52d92f9acea85e8b658af8183’:
    error: invalid path 'docs/data/documentation/bigint/bigint/!=(_:_:)-3bni3.json'
```

This structure is new in 5.4.0 from what I can tell

**Comment by tgymnich** [comment]
I reverted back to using jazzy from docc for now until this is fixed.
