### ISSUE TITLE
Add support for Swift 3.2 (Xcode 9)

### ISSUE THREAD

**Issue by serieuxchat** [attaswift/BigInt#20]
I know that it's a bit early now, but being able to compile with Xcode 9 (and Swift 3.2) would be really cool (since code completion and the editor in general is SO much nicer in the new Xcode).

**Comment by lorentey** [comment]
Agreed 100%! I'm still in San Jose with just my iPad; I won't be able to update BigInt until I get back to my Mac... If you have free time to do it, go for it! PRs are very welcome! ;)

BTW, Swift 4 has new integer protocols that make big integer libraries lot easier to implement & perform much faster. Updating to it is more work, but it'll definitely be worth the effort.

**Comment by konstantin-tcherkashin** [comment]
+1

**Comment by dropski** [comment]
Same here, iOS 11 arrive in 5 days ;) and Xcode 9 has much better flow than earlier versions

**Comment by jjv360** [comment]
Xcode 9 is out now and it can't build anymore... Any news on when support for Swift 3.2 will be added? Or at least a workaround we can use in the mean time?

**Comment by lorentey** [comment]
BigInt 3.0.0 supports (in fact, requires) Xcode 9 and Swift 4. It was released two weeks ago.

I did not test interoperability with Swift 3.2, but it is supposed to work. Please file new bugs if there are issues with that or with CocoaPods integration.

**Comment by konstantin-tcherkashin** [comment]
Cocoapods saying that last version is 2.1.2

**Comment by lorentey** [comment]
I pushed a button; the 3.0.0 pod should be available now.
