### ISSUE TITLE
SipHash dependency issue prevents BigInt's swift4 branch from being usable as a CocoaPod

### ISSUE THREAD

**Issue by brendan09** [attaswift/BigInt#22]

**Comment by lorentey** [comment]
Want to submit a quick PR to fix it?

**Comment by brendan09** [comment]
Yep, working on it now.

**Comment by brendan09** [comment]
This fix for this is actually in SipHash, so I made a PR there. Podspec files themselves can't point to branches, but typically an app can override the branch in their own Podfile. A naming issue in SipHash's podspec for source files on the swift4 branch prevented this from working for BigInt.

Merging this PR on SipHash's swift4 branch will allow the BigInt library to be built via Cocoapods (with a manual SipHash branch override in the app's Podfile).

Related PR on SipHash: https://github.com/attaswift/SipHash/pull/2
