### ISSUE TITLE
Value of type 'BigUInt' has no member 'reduce'

### ISSUE THREAD

**Issue by marcgug** [attaswift/BigInt#24]
After upgrading from 2.1.2 to 3.0.0 (and upgrading from Xcode 8.3.3 to 9.0), I am getting the error "Value of type 'BigUInt' has no member 'reduce'".

I see that 'reduce' is still mentioned in the [example in project readme](https://github.com/attaswift/BigInt), but has it been removed from the library?

**Comment by twodayslate** [comment]
[This is the `reduce`](https://developer.apple.com/documentation/swift/array/2298686-reduce) that is being used in the README

**Comment by marcgug** [comment]
Thanks for the info, @twodayslate. It turns out that `reduce` previously worked on integers (I think because they were considered a sequence), but no longer works on them in the latest version of Xcode.

This is unrelated to the BigInt library, so I'm closing this.
