### ISSUE TITLE
I am using  pod 'BigInt', '~> 2.1.0' and getting lot's of error

### ISSUE THREAD

**Issue by varun-naharia** [attaswift/BigInt#28]
![screen shot 2017-09-27 at 3 58 46 pm](https://user-images.githubusercontent.com/10987732/30908942-fb0c3f44-a39c-11e7-840d-407c72a9ec43.png)
please help

**Comment by dagerydoo** [comment]
Can you try upgrading to version `3.0.1`?

**Comment by Ybrin** [comment]
Upgrade to a higher version. This one is not supported any longer. If you have other problems feel free to open a new issue.
