### ISSUE TITLE
Release 3.0.1

### ISSUE THREAD

**Issue by dagerydoo** [attaswift/BigInt#30]
Hi @lorentey — I feel a bit uneasy making releases on this repo, but I did draft a new release with the latest bug fixes:

https://github.com/attaswift/BigInt/releases/tag/untagged-1100ee6296e800ded71d

I am not sure what the process is for releasing and pushing to cocoapods, etc, so I am leaving it like so. I am happy to learn and do it myself, but I didn't want to overstep my bounds here...

**Comment by lorentey** [comment]
If you have time available to make a new release, please do! I'll be eternally grateful. 🙏

To do a new release, I usually perform the following horrible list of steps:

- Increment the build number in version.xcconfig.
- Bump the version string in version.xcconfig and the .podspec.
- Update CHANGELOG.md with a description of the changes (your draft release notes are great!) Make sure you include the release date; it comes useful surprisingly often.
- Regenerate the documentation. (I "forgot" to do this for 3.0.0; if you have time, you may look into doing it now. No worries if not, though! I have not looked into using Jazzy with Swift 4 at all.) I used the `generate-docs.sh` script in previous releases; if you decide to do this, you may need to adapt it a little, but it should be a useful starting point.
- Commit and push all of the above
- Wait for Travis to make sure the build is still green
- Tag the new release as v3.0.1
- Run pod lint to see if CocoaPods likes you. You may need to push the new tag before this. (I guess you could set up some sort of private pod repo to test things out? I never read the docs.)
- Commit more stuff to fix any breakage, shamefully deleting and re-pushing the tag if necessary. (I’ve been really bad at release management... 🙈)
- Run `pod trunk push`, and hope that things turn out okay.

I have given you push access to your commit email to the pod repo, so you should be able to do the last step.

Let me know how it goes!

**Comment by dagerydoo** [comment]
I have run everything through the `pod spec lint` step, having merged https://github.com/attaswift/BigInt/pull/31 and tagged the repo (I had to delete my draft release, but it should be good now). I sent you an email earlier today about getting cocoapods push access.
