### ISSUE TITLE
Use of full width multiplication and division

### ISSUE THREAD

**Issue by mkrd** [attaswift/BigInt#33]
Since swift 4, the standard library implements "<UInt64>.multipliedFullWidth(by: <UInt64>) -> (<UInt64>, <UInt64>)" and an equivalent for division. The use of this might improve performance

**Comment by TG908** [comment]
`.multipliedFullWidth(by: ) -> (, ) `is already in use and our [implementation](https://github.com/attaswift/BigInt/blob/108801d539eb014469c758bc0d7f734690791fb4/Sources/Division.swift#L41) of division is faster than `.dividedFullWidth(by: ) -> (, )`
