### ISSUE TITLE
BigInt 2.1.2 with Xcode 9.2 and Swift 3.2

### ISSUE THREAD

**Issue by hoanghua** [attaswift/BigInt#36]
Hello,

Currently I'm using BigInit 2.1 with Xcode 8.3 and Swift 3.2 without any problem. However, after upgrading to BigInt 2.1.2 with Xcode 9.2 and Swift 3.2, I got the following error

![image](https://user-images.githubusercontent.com/483571/33801421-704636e6-dd8d-11e7-9507-8e0c81823a61.png)

Can you help to take a look to see if it's a known issue or if something wrong in my configuration?

Last but not least, thanks a lot for writing a great lib to work with big integer.

**Comment by Ybrin** [comment]
Please update BigInt to version 3.1.0 or above and use Swift 4.0 or above. We can't provide support for older versions any longer. If you have other problems feel free to open a new issue.
