### ISSUE TITLE
to [UInt8] array?

### ISSUE THREAD

**Issue by James-Sangalli** [attaswift/BigInt#39]
Will a function be added to cast a BigInt to a byte array like in Java's BigInteger?

**Comment by Ybrin** [comment]
Until it gets merged you can manually add an extension which does exactly this:

```

**Comment by Ybrin** [comment]
The initializer assumes to have a big endian UInt8 array and the `makeBytes` function creates a big endian UInt8 array

**Comment by TG908** [comment]
merged HaydenMcCabe approach.
