### ISSUE TITLE
BigInt 3.0.3 crash in xcode 9 swift 4

### ISSUE THREAD

**Issue by AdeSupriyadi** [attaswift/BigInt#40]
include by carthage
in cartfile: github "attaswift/BigInt" ~> 3.0

yld: Library not loaded: @rpath/SipHash.framework/SipHash
  Referenced from: /Users/<myuser>/Library/Developer/CoreSimulator/Devices/0A76CB65-0F98-4808-99A4-2C0B940D4C4F/data/Containers/Bundle/Application/153658BC-FB63-4CCA-B9F0-1E7AAE8ED4D5/<app-name>/Frameworks/BigInt.framework/BigInt
  Reason: image not found
(lldb)

**Comment by Ybrin** [comment]
Also see attaswift/SipHash#5

**Comment by Ybrin** [comment]
Please see [BigInt.swift](https://github.com/Boilertalk/BigInt.swift) until this gets fixed for Swift 4.1

**Comment by sunnycn2013** [comment]
I have got same error on device too, then it is good on simlator, When will have new version publish?

**Comment by sunnycn2013** [comment]
@lorentey

**Comment by Ybrin** [comment]
Fixed with version 3.1.0
