### ISSUE TITLE
Convert BigInt division to decimal?

### ISSUE THREAD

**Issue by bchrisarriola** [attaswift/BigInt#52]
I'm trying to convert the result of dividing two BigInt values into Decimal. For example, I'm trying to represent 10 / 1,000 into Decimal (i.e. 0.01). How can that be achieved?

**Comment by TG908** [comment]
The simplest way of doing this would be to convert the BigInt to a Decimal and perform the division on the Decimal. (*note: converting a BigInt to a Decimal may result in a loss of precision the division may add another loss of precision)

```
let x1 = BigInt(10)
let x2 = BigInt(1000)

let s1 = String(x1)
let s2 = String(x2)

let d1 = Decimal(string: s1)!
let d2 = Decimal(string: s2)!

let res = d1 / d2
```

For more precision you should consider using a library that offers a BigDouble type.
