### ISSUE TITLE
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler:

### ISSUE THREAD

**Issue by zhengyanfeng** [attaswift/BigInt#59]
I can't run on Xcode 10.2 and Swift

**Comment by TG908** [comment]
This sounds like you have to rebuild BigInt.

**Comment by zhengyanfeng** [comment]
> This sounds like you have to rebuild BigInt.

yeah, the BigInt do not support Swift 5.0 now

**Comment by TG908** [comment]
Thats odd. I just tried building a command line tool with Xcode 10.2 and BigInt using Carthage and it worked just fine. Carthage built BigInt using the swift 5.0 compiler. You can check the swift version used to build the framework by taking a look in `./BigInt.framework/Headers/BigInt-Swift.h`.
The first line will indicate the swift version used to build the framework:
For me it's `// Generated by Apple Swift version 5.0 effective-4.1.50 (swiftlang-1001.0.69.5 clang-1001.0.46.3)
`
