### ISSUE TITLE
Possibly deprecating some initializers.

### ISSUE THREAD

**Issue by HaydenMcCabe** [attaswift/BigInt#62]
Howdy.

I'm curious if some of the initializers should be deprecated:

For BigInt:
```
    public init?<T>(exactly source: T) where T : BinaryInteger {
        self.init(source)
    }

```
This optional initializer should never return nil, as any value that can be represented by a BinaryInteger can be represented as a BigInt, as BigInt has a wider possible range than any fixed-size integer type.

```
    public init<T>(clamping source: T) where T : BinaryInteger {
        self.init(source)
    }
```
Similarly, clamping is not needed, as BigInt has the needed range to cover any fixed-width BinaryInteger type.

```
    public init<T>(truncatingIfNeeded source: T) where T : BinaryInteger {
        self.init(source)
    }
```
Truncating doesn't seem to apply to the case of initializing a BigInt from another Integer value

For BigUInt:

```
    public init<T: BinaryInteger>(truncatingIfNeeded source: T) {
        self.init(words: source.words)
    }
```
As for BigInt, it seems there won't be a case where truncating would be needed.

 ```
   public init?<T: BinaryInteger>(exactly source: T) {
        guard source >= (0 as T) else { return nil }
        if source.bitWidth <= 2 * Word.bitWidth {
            var it = source.words.makeIterator()
            self.init(low: it.next() ?? 0, high: it.next() ?? 0)
            precondition(it.next() == nil, "Length of BinaryInteger.words is greater than its bitWidth")
        }
        else {
            self.init(words: source.words)
        }
    }

    public init<T: BinaryInteger>(_ source: T) {
        precondition(source >= (0 as T), "BigUInt cannot represent negative values")
        self.init(exactly: source)!
    }
```
With this pair of initializers, the first, optional initializer seems like it would correctly return nil for negative values, and an exact value for a non-negative argument. The second initializer, however, gives the same results, with the code crashing if a negative value is used. Perhaps they could be consolidated into a single optional initializer without precondition.

**Comment by TG908** [comment]
The clamping, truncating and exactly initializers are part of the [BinaryInteger](https://developer.apple.com/documentation/swift/binaryinteger) protocol.  Which servers as the basis for all the integer types provided by the Swift standard library.

Concerning: `public init<T: BinaryInteger>(_ source: T)` all integer types in swift have a initializer that could potentially crash (eg. UInt8, ...).

We want to keep our API as close to the Swift standard library as possible. Therefore I think no changes are necessary.
