### ISSUE TITLE
crash if send string or invalid data to BigInt

### ISSUE THREAD

**Issue by thepinyo** [attaswift/BigInt#63]
i found crash if send invalid data to BigInt.
i think shouldn't use force unwrap inside your method and check value before use.

![Screen Shot 2562-08-21 at 09 59 27](https://user-images.githubusercontent.com/10898349/63399698-8a89b900-c3fb-11e9-8f41-6ae60f2b8ab3.png)

```
/// Initialize a new big integer from a decimal number represented by a string literal of arbitrary length.
/// The string must contain only decimal digits.

public init(stringLiteral value: StringLiteralType) {
    self = BigInt(value, radix: 10)!
}
```

**Comment by TG908** [comment]
[ExpressibleByStringLiteral](https://developer.apple.com/documentation/swift/expressiblebystringliteral) requires us to implement a non-failable initializer. Thus we cannot avoid a crash on invalid values. You can use the following in failable initializer to avoid the crash and get an optional: `public init?<S: StringProtocol>(_ text: S, radix: Int = 10)`

**Comment by mefilt** [comment]
@tgymnich Do you have method for validation string?

**Comment by tgymnich** [comment]
@mefilt you can use the failable initializer:
```
let y = "Test"
let x: BigInt? = BigInt(y)
print(x) // nil
```
