### ISSUE TITLE
Release 5.1.0 cocoapod

### ISSUE THREAD

**Issue by RockLobster** [attaswift/BigInt#70]
Hi there, i saw that you made a release 5.1 for BigInt.
Unfortunately, it does not seem to be available via cocoapods.

> None of your spec sources contain a spec satisfying the dependency: `BigInt (= 5.1.0)`

Could you push it to cocoapods?

**Comment by koraykoska** [comment]
Done see #74

**Comment by koraykoska** [comment]
Please use 5.2.0 from now on
