### ISSUE TITLE
Please publish version 5.2.0 (and future versions) on CocoaPods

### ISSUE THREAD

**Issue by phirk** [attaswift/BigInt#74]
Similar to #70 and #67, would you please be so kind to publish version 5.2.0 (and future versions) on CocoaPods?

If there's a reason you are no longer doing this and we should integrate your module in a different way now, please let us know.

**Comment by koraykoska** [comment]
I am on it.

**Comment by TG908** [comment]
It might be a good idea to setup a GitHub action to do this

**Comment by koraykoska** [comment]
@phirk Done. See https://raw.githubusercontent.com/CocoaPods/Specs/310bbbdea03b6c166ca5a0eca47216adb9fadf92/Specs/6/5/b/BigInt/5.2.0/BigInt.podspec.json

@TG908 Yeah I mean make a PR if you want. Our release cycle is more or less once every few months so somehow it's more trouble than worth it I guess but I will happily accept a PR which pushes it to cocoapods on master merges.
