### ISSUE TITLE
Library evolution support

### ISSUE THREAD

**Issue by NathanFallet** [attaswift/BigInt#83]
When importing `BigInt` on my project (using it for a [RSA implementation](https://github.com/krzyzanowskim/CryptoSwift/pull/887) in [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift)), I'm getting this warning:

> Module 'BigInt' was not compiled with library evolution support; using it means binary compatibility for 'CryptoSwift' can't be guaranteed

See https://swift.org/blog/library-evolution/ for details about how to fix it.

**Comment by tgymnich** [comment]
See #84

**Comment by NathanFallet** [comment]
@tgymnich Then how can I fix this warning?

Step to reproduce:
```terminal
git clone https://github.com/NathanFallet/CryptoSwift
cd CryptoSwift
git checkout rsa
open CryptoSwift.xcodeproj
```
And navigate to `Sources/CryptoSwift/RSA.swift` to see the warning

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/30439790/131243798-1d47d132-5dd8-4751-aaa5-1d1cc11a8541.png">

**Comment by tgymnich** [comment]
Your example uses the BigInt swift package. Swift packages are not affected by changes to the Xcode project settings. Further swift package manager [does not support enabling library evolution support](https://forums.swift.org/t/how-to-enable-library-evolution-support-for-swift-package/47191/3).

**Comment by NathanFallet** [comment]
@krzyzanowskim What's your opinion on this, and what would be your preferred way to import BigInt into CryptoSwift? (To be ok with SPM, CocoaPods, Carthage and Framework)

**Comment by tgymnich** [comment]
[This](https://github.com/tgymnich/CryptoSwift/tree/rsa) is how I would do it.
I might also add the swift package dependency back to the Xcode project and just ignore the warning. Otherwise people would need to use Carthage, CocoaPods or Swift Package manager to develop CryptoSwift
