### ISSUE TITLE
BigInt 5.3.0 not present on CocoaPods

### ISSUE THREAD

**Issue by AlonsoFloo** [attaswift/BigInt#94]
Hello,

I've wanted to update BigInt from version 5.2.0 to 5.3.0, yet the CocoaPodsSpecs is not present.
- https://cocoapods.org/pods/BigInt
- https://github.com/CocoaPods/Specs/tree/master/Specs/6/5/b/BigInt

Is CocoaPods still supported ?
Can I do anything to help ?

**Comment by AlonsoFloo** [comment]
Shall we assume coca pods will not be updated beyond 5.2.0 ?

Is there anything I can do to help ? 
Could we add more contributor to CocoaPods Trunk for redundency ?

**Comment by yaroslavyaroslav** [comment]
> This workaround might be helpful until we can resolve this issue:
> 
> ```
> pod 'BigInt', :git => 'https://github.com/attaswift/BigInt', :tag => 'v5.3.0'
> ```

This unfortunately doesn't work within podspec.

**Comment by tgymnich** [comment]
CocoaPods is no longer supported. Please consider using swift package manager.

**Comment by riderx** [comment]
There is app who cannot use Package manager, please explain us why removing cocoa was important? it does make no sense

**Comment by riderx** [comment]
@tgymnich this is still issue today, i will hvae to drop Bigint because you cannot take 5 sec to publish latest...
